server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json;charset=UTF-8

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

spring:
  datasource:
    url: jdbc:mysql://47.101.201.21:3306/bus?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: password      #wpg@admin18
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
